name: CI

on: [push]

jobs:
  build:

    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        pip install pyinstaller
        pyinstaller -F form.py
        git add .
        git commit -m '2233'
        dir dist
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: form.py
        # Directory containing files to upload
        path: form.py
