name: CI

on: [push]

jobs:
  build:

    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        pip install pyinstaller
        pyinstaller -F form.py
        git add .
        git commit -m '2233'
        git push origin master
    - name : Upload artifact
        uses: actions/upload-artifact@master
        with:
        name: OpenWrt
        path: openwrt/bin
